# meedan/elasticsearch
# elasticsearch 2.3 with elasticsearch-gui plugin

FROM elasticsearch:latest
MAINTAINER sysops@meedan.com

# https://github.com/jettro/elasticsearch-gui
RUN plugin install jettro/elasticsearch-gui 
