# meedan/elasticsearch
# elasticsearch 2.3 with the marvel and elasticsearch-gui plugins

FROM elasticsearch:latest
MAINTAINER sysops@meedan.com

# removing marvel at Karim's request
# RUN plugin install license
# RUN plugin install marvel-agent

# https://github.com/jettro/elasticsearch-gui
RUN plugin install jettro/elasticsearch-gui 
