# meedan/elasticsearch
# elasticsearch 2.4 with elasticsearch-gui plugin

FROM elasticsearch:2.4
MAINTAINER sysops@meedan.com

# https://github.com/jettro/elasticsearch-gui
RUN plugin install jettro/elasticsearch-gui 
